"""initial schema - 9 tables

Revision ID: fb90a931a728
Revises: 
Create Date: 2026-04-03 14:59:29.680342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb90a931a728'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plateformes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('url_base', sa.String(length=500), nullable=False),
    sa.Column('type_contenu', sa.String(length=50), nullable=False),
    sa.Column('adapter_class', sa.String(length=200), nullable=False),
    sa.Column('da_actuel', sa.Float(), nullable=True),
    sa.Column('dofollow', sa.Boolean(), nullable=False),
    sa.Column('inscription_requise', sa.Boolean(), nullable=False),
    sa.Column('difficulte_posting', sa.String(length=20), nullable=False),
    sa.Column('thematiques', sa.JSON(), nullable=True),
    sa.Column('score_composite', sa.Float(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('domaine', sa.String(length=200), nullable=False),
    sa.Column('url_base', sa.String(length=500), nullable=False),
    sa.Column('thematiques', sa.JSON(), nullable=True),
    sa.Column('rythme_diffusion_jour', sa.Integer(), nullable=False),
    sa.Column('ga4_property_id', sa.String(length=50), nullable=True),
    sa.Column('gsc_site_url', sa.String(length=500), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('analytics_seo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('page_url', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('avg_position', sa.Float(), nullable=True),
    sa.Column('keywords_top10', sa.Integer(), nullable=False),
    sa.Column('keywords_top30', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comptes_plateforme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plateforme_id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=True),
    sa.Column('identifiant', sa.String(length=200), nullable=False),
    sa.Column('mot_de_passe_chiffre', sa.String(length=500), nullable=True),
    sa.Column('cookies_session', sa.Text(), nullable=True),
    sa.Column('token_api', sa.String(length=500), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('dernier_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plateforme_id'], ['plateformes.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contenus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=500), nullable=False),
    sa.Column('url_source', sa.String(length=1000), nullable=False),
    sa.Column('contenu_brut', sa.Text(), nullable=True),
    sa.Column('mots_cles', sa.JSON(), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_da_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plateforme_id', sa.Integer(), nullable=False),
    sa.Column('da_value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plateforme_id'], ['plateformes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_da_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('da_value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu_id', sa.Integer(), nullable=False),
    sa.Column('plateforme_id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('url_publie', sa.String(length=1000), nullable=True),
    sa.Column('utm_params', sa.JSON(), nullable=True),
    sa.Column('titre_adapte', sa.String(length=500), nullable=True),
    sa.Column('contenu_adapte', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('dofollow_confirme', sa.Boolean(), nullable=True),
    sa.Column('derniere_verification', sa.DateTime(), nullable=True),
    sa.Column('nb_verifications_ok', sa.Integer(), nullable=False),
    sa.Column('nb_erreurs_consecutives', sa.Integer(), nullable=False),
    sa.Column('erreur_detail', sa.Text(), nullable=True),
    sa.Column('tentatives', sa.Integer(), nullable=False),
    sa.Column('publie_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contenu_id'], ['contenus.id'], ),
    sa.ForeignKeyConstraint(['plateforme_id'], ['plateformes.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_traffic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('plateforme_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('avg_session_duration', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plateforme_id'], ['plateformes.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics_traffic')
    op.drop_table('posts')
    op.drop_table('project_da_history')
    op.drop_table('platform_da_history')
    op.drop_table('contenus')
    op.drop_table('comptes_plateforme')
    op.drop_table('analytics_seo')
    op.drop_table('projets')
    op.drop_table('plateformes')
    # ### end Alembic commands ###
